doctrine:
    dbal:
        gateway:
            driver:    pdo_mysql
            host:      localhost
            dbname:    b2b_gateway
            user:      root
            password:  root
            charset:   UTF8
raecClient:
    baseUri: http://catalog.raec.su/api/
    apiKey:  secret_key